server:
  port: 8090
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_agency?useSSL=false
    # driver-class-name: org.mysql.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

# Custom properties
app:
  security:
    in-app-token:
      duration: 1
    jwt:
      secret-key: 5fbea5ec7f0625a059be825d829b533487aeeafe45b974d0d88b9a17ba33117e
      token:
        expiration: 86400000
    filter:
      header: "Bearer "