server:
  port: 8090
  servlet:
    context-path: /api
spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      location: D:/User Data/portfolio/real-estate-agency/backend/uploads
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_agency?useSSL=false
    # driver-class-name: org.mysql.Driver
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: always
logging:
  level:
    root: WARN


# Custom properties
app:
  security:
    in-app-token:
      duration: 1
    jwt:
      secret-key: 5fbea5ec7f0625a059be825d829b533487aeeafe45b974d0d88b9a17ba33117e
      token:
        expiration: 86400000
    filter:
      header: "Bearer "