spring:
  datasource:
    url: jdbc:h2:mem:real_estate_agency
    driver-class-name: org.h2.Driver
    username: root
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
